# Squirrel multiclass detection — YOLO26 Medium (v2)

Complete workflow: audited dataset → immutable YOLO conversion → model/GPU verification → memory probe → training → validation/test reports → CPU/GPU benchmarks → model package.

**Task:** eleven-class bounding-box detection, with ten species plus `generic_squirrel`.
**Recipe:** pretrained medium model, 640 pixels, standard native YOLO sampling/augmentations, seed 42, AMP, **at most 200 epochs and early-stopping patience 30**.

Run `uv sync --locked --all-extras` before selecting the project `.venv` kernel. Run cells in order. The training cell starts the full experiment; preparation and probe cells do not. Generated files stay under `output_yolo26/runs/<run-id>/`.

Recover an interrupted experiment by setting `RESUME_RUN` below and keeping its configuration unchanged. Complete checkpoints remain frozen for validation/test. Source COCO images and splits are never modified.

YOLO26 reports both its accuracy-oriented and NMS-free heads from independent loads of the same checkpoint. Original YOLOv5 uses `yolov5m.pt`, not the anchor-free YOLOv5u variant.

In [1]:
# 1. Nonsecret configuration and independent run folder.
from pathlib import Path
import json
from IPython.display import display, HTML, IFrame
from csci_635_ml_project.baseline import (
    default_config, create_run, prepare_run, probe_batches, train_run,
    predict_run, benchmark_run, package_run,
)
from csci_635_ml_project.baseline_reports import dataset_report, evaluate_run

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").exists())
DATA = ROOT / "data/squirrel-v2-audited-coco"
CFG = default_config("yolo26")  # epochs=200, patience=30, imgsz=640, seed=42
RESUME_RUN = None  # ROOT / "output_yolo26/runs/<run-id>"
RUN = create_run(ROOT, CFG, resume_run=RESUME_RUN, data=DATA)
print("Run:", RUN)
display(CFG)

Run: /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f

{'model': 'yolo26',
 'epochs': 200,
 'patience': 30,
 'imgsz': 640,
 'seed': 42,
 'batch_candidates': [16, 8, 4],
 'workers': 4,
 'amp': True,
 'save_period': 10,
 'optimizer': 'auto',
 'prediction_floor': 0.0001,
 'max_detections': 100,
 'matching_iou': 0.5,
 'nms_iou': 0.7,
 'heads': ['accuracy', 'end2end'],
 'ultralytics_version': '8.4.164',
 'yolov5_commit': '402e17ddf820996f51a191cbb798376e1144f069',
 'benchmark_images': 200,
 'benchmark_warmup': 20,
 'cpu_threads': 1}

## 2. Dataset verification, EDA, and backend setup

Require the passing audited v3 manifest and matching annotation hashes. Export the exact splits and class mapping to a fingerprinted YOLO dataset; every subsequent use verifies its image and label hashes. Native caches use the converted copy. Backend setup pins the model/source version, records pretrained weights and environment hashes, and executes a CUDA kernel.

In [2]:
DATA_YAML = prepare_run(RUN)
class_counts = dataset_report(RUN, DATA)
display(class_counts)
print("YOLO dataset:", DATA_YAML)
display(IFrame(src=str((RUN / "reports/report.html").relative_to(ROOT)), width="100%", height=700))

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/.ultralytics/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/usage/settings.

    split               class_name  images  annotations
0   train  Callosciurus erythraeus     501          533
1   train      Sciurus aureogaster     534          570
2   train     Sciurus carolinensis     666          692
3   train      Sciurus granatensis     547          566
4   train          Sciurus griseus     581          655
5   train              Sciurus lis     409          449
6   train            Sciurus niger     551          606
7   train         Sciurus vulgaris     529          564
8   train   Tamiasciurus douglasii     574          591
9   train  Tamiasciurus hudsonicus     566          589
10  train         generic_squirrel     530          564
11  valid  Callosciurus erythraeus     107          111
12  valid      Sciurus aureogaster     115          122
13  valid     Sciurus carolinensis     143          151
14  valid      Sciurus granatensis     117          123
15  valid          Sciurus griseus     124          133
16  valid              Sciurus lis      87           96
17  valid            Sciurus niger     118          124
18  valid         Sciurus vulgaris     113          120
19  valid   Tamiasciurus douglasii     123          127
20  valid  Tamiasciurus hudsonicus     122          123
21  valid         generic_squirrel     113          120
22   test  Callosciurus erythraeus     108          121
23   test      Sciurus aureogaster     114          123
24   test     Sciurus carolinensis     144          157
25   test      Sciurus granatensis     117          124
26   test          Sciurus griseus     124          132
27   test              Sciurus lis      87           94
28   test            Sciurus niger     118          126
29   test         Sciurus vulgaris     114          126
30   test   Tamiasciurus douglasii     123          131
31   test  Tamiasciurus hudsonicus     122          124
32   test         generic_squirrel     113          122

YOLO dataset: /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/data.yaml

## 3. GPU memory probe

Try batches 16, 8, then 4 on a small seeded train/validation sample. Only CUDA OOM triggers a smaller-batch retry. Native nominal batch size is 64; resolved settings are saved. Probe weights are discarded for full training. Probe folders include batch-loss traces and a short Torch profiler trace where supported.

In [3]:
selected = probe_batches(RUN)
display(selected)

USDT:2026-09-28 16:22:18 2220647:2220647 SyncActivityProfilerHandler.cpp:39] profiler_start
New https://pypi.org/project/ultralytics/8.4.165 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.164 🚀 Python-3.13.15 torch-2.14.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5060 Ti, 15938MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probe_data/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=1, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/pretrained/yolo26m.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=batch-16-008c0f, nbs=64, nms=None, opset=None, optimize=False, optimizer=MuSGD, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None

Downloading https://ultralytics.com/assets/Arial.ttf to '/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/.ultralytics/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 16.5MB/s 0.0s
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    542720  ultralytics.nn.modules.block.C3k2            [1024, 256, 1, True]
 17                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 20                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1974784  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1   2815578  ultralytics.nn.modules.head.Detect           [11, 1, True, [256, 512, 512]]
YOLO26m summary: 280 layers, 21,789,850 parameters, 21,789,850 gradients, 75.0 GFLOPs

Transferred 756/768 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 5798.3±576.8 MB/s, size: 493.5 KB)

train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 98 images, 0 backgrounds, 0 corrupt: 76% ━━━━━━━━━─── 98/128 290.9it/s 0.1s<0.1s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 128 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 128/128 1.1Kit/s 0.1s
train: New cache created: /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4312.8±656.7 MB/s, size: 387.2 KB)

val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 32 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 32/32 1.0Kit/s 0.0s
val: New cache created: /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid.cache
optimizer: MuSGD(lr=0.01, momentum=0.937) with parameter groups 124 weight(decay=0.0), 136 weight(decay=0.0005), 136 bias(decay=0.0)
Plotting labels to /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f/labels.jpg...
Using 128 train, 32 val images for fraction=1.0 at imgsz=640
Using 4 dataloader workers
Logging results to /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f
Starting training for 1 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

        1/1      8.71G      1.168      18.36    0.01352         16        640: 0% ──────────── 0/8  10.3s
        1/1      8.74G       1.05      17.05    0.01143         18        640: 12% ━─────────── 1/8 1.4s/it 10.7s<9.8s[W928 16:22:41.985666328 CPUAllocator.cpp:245] Memory block of unknown size was allocated before the profiling started, profiler results will not include the deallocation event

        1/1      8.74G      1.149      17.13    0.01299         18        640: 25% ━━━───────── 2/8 1.2it/s 11.1s<4.9s
        1/1      8.74G      1.115      16.82     0.0141         18        640: 37% ━━━━──────── 3/8 1.2it/s 12.0s<4.1s
        1/1      8.74G      1.111      16.86    0.01366         17        640: 50% ━━━━━━────── 4/8 1.9it/s 12.3s<2.2s
        1/1      8.74G      1.097      17.02    0.01349         16        640: 62% ━━━━━━━───── 5/8 2.2it/s 12.6s<1.4s
        1/1      8.74G      1.089      17.12    0.01325         16        640: 75% ━━━━━━━━━─── 6/8 2.5it/s 12.9s<0.8s
        1/1      8.74G      1.095      16.92    0.01342         19        640: 87% ━━━━━━━━━━── 7/8 2.7it/s 13.3s<0.4s
        1/1      8.74G      1.095      16.92    0.01342         19        640: 100% ━━━━━━━━━━━━ 8/8 1.7s/it 13.3s

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.3it/s 0.8s
                   all         32         35      0.933        0.1      0.149      0.123

1 epochs completed in 0.005 hours.
Optimizer stripped from /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f/weights/last.pt, 44.0MB
Optimizer stripped from /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f/weights/best.pt, 44.0MB

Validating /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f/weights/best.pt...
Ultralytics 8.4.164 🚀 Python-3.13.15 torch-2.14.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5060 Ti, 15938MiB)
YOLO26m summary (fused): 130 layers, 20,357,933 parameters, 0 gradients, 68.1 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5it/s 0.7s
                   all         32         35      0.933        0.1      0.151      0.124
Callosciurus erythraeus          1          1      0.333          1      0.995      0.895
   Sciurus aureogaster          5          5          1          0     0.0296     0.0139
  Sciurus carolinensis          2          2          1          0     0.0895     0.0855
   Sciurus granatensis          2          2          1          0     0.0381     0.0188
       Sciurus griseus          3          3          1          0     0.0494     0.0272
         Sciurus niger          4          4          1          0      0.049     0.0441
      Sciurus vulgaris          5          7          1          0    0.00336    0.00242
Tamiasciurus douglasii          4          4          1          0      0.189      0.104
Tamiasciurus hudsonicus          2          2          1          0     0.0275     0.0138
      generic_squirrel          4          5          1          0     0.0366     0.0312
Speed: 0.2ms preprocess, 7.6ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/probes/batch-16-008c0f
USDT:2026-09-28 16:22:56 2220647:2220647 SyncActivityProfilerHandler.cpp:46] profiler_stop

{'batch_size': 16,
 'nominal_batch': 64,
 'attempts': [{'batch': 16, 'status': 'passed'}],
 'peak_vram_gib': 8.311372756958008}

## 4. Full training — this cell starts the experiment

Use the native optimizer/augmentation recipe with up to 200 epochs and 30-epoch early-stopping patience. YOLO26 selects its checkpoint by validation mAP50–95; original YOLOv5 uses 0.1 × AP50 + 0.9 × mAP50–95. Keep best/latest, periodic, and unstripped recovery checkpoints. Training logs, batch losses, epoch metrics, timing, VRAM, and loss curves stay in this run.

In [4]:
if (RUN / "training_complete.json").exists():
    print("Training already completed; using the frozen best checkpoint.")
else:
    history = train_run(RUN)
    display(history.tail())

New https://pypi.org/project/ultralytics/8.4.165 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.4.164 🚀 Python-3.13.15 torch-2.14.0+cu130 CUDA:0 (NVIDIA GeForce RTX 5060 Ti, 15938MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/data.yaml, degrees=0.0, deterministic=True, device=0, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=200, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, iou=0.7, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/pretrained/yolo26m.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=native, nbs=64, nms=None, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/native, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=4, workspace=None
Overriding model.yaml nc=80 with nc=11

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  1    111872  ultralytics.nn.modules.block.C3k2            [128, 256, 1, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  1    444928  ultralytics.nn.modules.block.C3k2            [256, 512, 1, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  1   1380352  ultralytics.nn.modules.block.C3k2            [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  1    990976  ultralytics.nn.modules.block.C2PSA           [512, 512, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1   1642496  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1    542720  ultralytics.nn.modules.block.C3k2            [1024, 256, 1, True]
 17                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1   1511424  ultralytics.nn.modules.block.C3k2            [768, 512, 1, True]
 20                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1974784  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1   2815578  ultralytics.nn.modules.head.Detect           [11, 1, True, [256, 512, 512]]
YOLO26m summary: 280 layers, 21,789,850 parameters, 21,789,850 gradients, 75.0 GFLOPs

Transferred 756/768 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4326.6±1218.4 MB/s, size: 317.7 KB)

train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 85 images, 0 backgrounds, 0 corrupt: 1% ──────────── 85/5988 248.4it/s 0.1s<23.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 187 images, 0 backgrounds, 0 corrupt: 3% ──────────── 187/5988 477.6it/s 0.2s<12.1s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 288 images, 0 backgrounds, 0 corrupt: 4% ╸─────────── 288/5988 634.4it/s 0.3s<9.0s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 380 images, 0 backgrounds, 0 corrupt: 6% ╸─────────── 380/5988 719.3it/s 0.4s<7.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 477 images, 0 backgrounds, 0 corrupt: 7% ╸─────────── 477/5988 781.9it/s 0.5s<7.0s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 580 images, 0 backgrounds, 0 corrupt: 9% ━─────────── 580/5988 854.2it/s 0.6s<6.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 679 images, 0 backgrounds, 0 corrupt: 11% ━─────────── 679/5988 876.8it/s 0.7s<6.1s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 782 images, 0 backgrounds, 0 corrupt: 13% ━╸────────── 782/5988 922.7it/s 0.8s<5.6s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 883 images, 0 backgrounds, 0 corrupt: 14% ━╸────────── 883/5988 939.3it/s 0.9s<5.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1011 images, 0 backgrounds, 0 corrupt: 16% ━━────────── 1011/5988 1.0Kit/s 1.0s<4.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1107 images, 0 backgrounds, 0 corrupt: 18% ━━────────── 1107/5988 1.0Kit/s 1.1s<4.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1201 images, 0 backgrounds, 0 corrupt: 20% ━━────────── 1201/5988 971.4it/s 1.2s<4.9s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1309 images, 0 backgrounds, 0 corrupt: 21% ━━╸───────── 1309/5988 998.6it/s 1.3s<4.7s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1421 images, 0 backgrounds, 0 corrupt: 23% ━━╸───────── 1421/5988 1.0Kit/s 1.4s<4.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1522 images, 0 backgrounds, 0 corrupt: 25% ━━━───────── 1522/5988 1.0Kit/s 1.5s<4.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1620 images, 0 backgrounds, 0 corrupt: 27% ━━━───────── 1620/5988 1.0Kit/s 1.6s<4.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1719 images, 0 backgrounds, 0 corrupt: 28% ━━━───────── 1719/5988 987.0it/s 1.7s<4.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1830 images, 0 backgrounds, 0 corrupt: 30% ━━━╸──────── 1830/5988 1.0Kit/s 1.8s<4.1s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 1931 images, 0 backgrounds, 0 corrupt: 32% ━━━╸──────── 1931/5988 1.0Kit/s 1.9s<4.0s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2025 images, 0 backgrounds, 0 corrupt: 33% ━━━━──────── 2025/5988 990.1it/s 2.0s<4.0s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2132 images, 0 backgrounds, 0 corrupt: 35% ━━━━──────── 2132/5988 1.0Kit/s 2.1s<3.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2228 images, 0 backgrounds, 0 corrupt: 37% ━━━━──────── 2228/5988 982.9it/s 2.2s<3.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2309 images, 0 backgrounds, 0 corrupt: 38% ━━━━╸─────── 2309/5988 928.6it/s 2.3s<4.0s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2443 images, 0 backgrounds, 0 corrupt: 40% ━━━━╸─────── 2443/5988 1.0Kit/s 2.5s<3.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2549 images, 0 backgrounds, 0 corrupt: 42% ━━━━━─────── 2549/5988 1.0Kit/s 2.6s<3.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2644 images, 0 backgrounds, 0 corrupt: 44% ━━━━━─────── 2644/5988 1.0Kit/s 2.7s<3.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2744 images, 0 backgrounds, 0 corrupt: 45% ━━━━━─────── 2744/5988 1.0Kit/s 2.8s<3.2s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2836 images, 0 backgrounds, 0 corrupt: 47% ━━━━━╸────── 2836/5988 973.5it/s 2.9s<3.2s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 2948 images, 0 backgrounds, 0 corrupt: 49% ━━━━━╸────── 2948/5988 1.0Kit/s 3.0s<3.0s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3047 images, 0 backgrounds, 0 corrupt: 50% ━━━━━━────── 3047/5988 1.0Kit/s 3.1s<2.9s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3142 images, 0 backgrounds, 0 corrupt: 52% ━━━━━━────── 3142/5988 981.2it/s 3.2s<2.9s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3248 images, 0 backgrounds, 0 corrupt: 54% ━━━━━━╸───── 3248/5988 1.0Kit/s 3.3s<2.7s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3347 images, 0 backgrounds, 0 corrupt: 55% ━━━━━━╸───── 3347/5988 984.3it/s 3.4s<2.7s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3463 images, 0 backgrounds, 0 corrupt: 57% ━━━━━━╸───── 3463/5988 1.0Kit/s 3.5s<2.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3555 images, 0 backgrounds, 0 corrupt: 59% ━━━━━━━───── 3555/5988 997.1it/s 3.6s<2.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3657 images, 0 backgrounds, 0 corrupt: 61% ━━━━━━━───── 3657/5988 997.4it/s 3.7s<2.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3742 images, 0 backgrounds, 0 corrupt: 62% ━━━━━━━───── 3742/5988 953.0it/s 3.8s<2.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3841 images, 0 backgrounds, 0 corrupt: 64% ━━━━━━━╸──── 3841/5988 958.9it/s 3.9s<2.2s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 3934 images, 0 backgrounds, 0 corrupt: 65% ━━━━━━━╸──── 3934/5988 949.4it/s 4.0s<2.2s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4046 images, 0 backgrounds, 0 corrupt: 67% ━━━━━━━━──── 4046/5988 996.3it/s 4.1s<1.9s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4150 images, 0 backgrounds, 0 corrupt: 69% ━━━━━━━━──── 4150/5988 1.0Kit/s 4.2s<1.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4242 images, 0 backgrounds, 0 corrupt: 70% ━━━━━━━━╸─── 4242/5988 969.7it/s 4.3s<1.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4338 images, 0 backgrounds, 0 corrupt: 72% ━━━━━━━━╸─── 4338/5988 956.5it/s 4.4s<1.7s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4436 images, 0 backgrounds, 0 corrupt: 74% ━━━━━━━━╸─── 4436/5988 963.0it/s 4.5s<1.6s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4537 images, 0 backgrounds, 0 corrupt: 75% ━━━━━━━━━─── 4537/5988 974.7it/s 4.6s<1.5s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4632 images, 0 backgrounds, 0 corrupt: 77% ━━━━━━━━━─── 4632/5988 949.2it/s 4.7s<1.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4730 images, 0 backgrounds, 0 corrupt: 78% ━━━━━━━━━─── 4730/5988 957.7it/s 4.8s<1.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4819 images, 0 backgrounds, 0 corrupt: 80% ━━━━━━━━━╸── 4819/5988 927.1it/s 4.9s<1.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 4904 images, 0 backgrounds, 0 corrupt: 81% ━━━━━━━━━╸── 4904/5988 902.9it/s 5.0s<1.2s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5002 images, 0 backgrounds, 0 corrupt: 83% ━━━━━━━━━━── 5002/5988 914.0it/s 5.1s<1.1s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5109 images, 0 backgrounds, 0 corrupt: 85% ━━━━━━━━━━── 5109/5988 958.0it/s 5.2s<0.9s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5203 images, 0 backgrounds, 0 corrupt: 86% ━━━━━━━━━━── 5203/5988 937.5it/s 5.3s<0.8s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5305 images, 0 backgrounds, 0 corrupt: 88% ━━━━━━━━━━╸─ 5305/5988 962.2it/s 5.4s<0.7s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5405 images, 0 backgrounds, 0 corrupt: 90% ━━━━━━━━━━╸─ 5405/5988 969.4it/s 5.5s<0.6s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5508 images, 0 backgrounds, 0 corrupt: 91% ━━━━━━━━━━━─ 5508/5988 984.1it/s 5.6s<0.5s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5606 images, 0 backgrounds, 0 corrupt: 93% ━━━━━━━━━━━─ 5606/5988 980.4it/s 5.7s<0.4s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5706 images, 0 backgrounds, 0 corrupt: 95% ━━━━━━━━━━━─ 5706/5988 984.1it/s 5.8s<0.3s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5805 images, 0 backgrounds, 0 corrupt: 96% ━━━━━━━━━━━╸ 5805/5988 984.1it/s 5.9s<0.2s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5895 images, 0 backgrounds, 0 corrupt: 98% ━━━━━━━━━━━╸ 5895/5988 954.5it/s 6.0s<0.1s
train: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train... 5988 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 5988/5988 980.9it/s 6.1s
train: New cache created: /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/train.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 6053.9±795.6 MB/s, size: 342.5 KB)

val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 88 images, 0 backgrounds, 0 corrupt: 6% ╸─────────── 88/1282 237.9it/s 0.1s<5.0s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 194 images, 0 backgrounds, 0 corrupt: 15% ━╸────────── 194/1282 473.0it/s 0.2s<2.3s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 302 images, 0 backgrounds, 0 corrupt: 23% ━━╸───────── 302/1282 640.4it/s 0.3s<1.5s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 401 images, 0 backgrounds, 0 corrupt: 31% ━━━╸──────── 401/1282 742.8it/s 0.4s<1.2s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 493 images, 0 backgrounds, 0 corrupt: 38% ━━━━╸─────── 493/1282 783.8it/s 0.5s<1.0s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 591 images, 0 backgrounds, 0 corrupt: 46% ━━━━━╸────── 591/1282 840.9it/s 0.6s<0.8s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 715 images, 0 backgrounds, 0 corrupt: 55% ━━━━━━╸───── 715/1282 954.6it/s 0.7s<0.6s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 810 images, 0 backgrounds, 0 corrupt: 63% ━━━━━━━╸──── 810/1282 943.5it/s 0.8s<0.5s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 906 images, 0 backgrounds, 0 corrupt: 70% ━━━━━━━━──── 906/1282 940.3it/s 0.9s<0.4s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 988 images, 0 backgrounds, 0 corrupt: 77% ━━━━━━━━━─── 988/1282 904.1it/s 1.0s<0.3s
val: Scanning /home/ss3813/github/ML/CSCI-635-ML-Project/data/squirrel-v2-audited-yolo/96af70a0474fdebe/labels/valid... 1093 images, 0 backgrounds, 0 corrupt: 85% ━━━━━━━━━━── 1093/1282 947.8it/s 1.1s<0.2s

,epoch,time,train/box_loss,train/cls_loss,train/l1_loss,metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),val/box_loss,...,lr/pg0,lr/pg1,lr/pg2,lr/pg3,lr/pg4,lr/pg5,lr/pg6,lr/pg7,seconds,peak_vram_gib
135,136,12626.6,0.62739,0.45424,0.00694,0.76361,0.68495,0.72526,0.53427,0.95978,...,0.009952,0.003318,0.009952,0.003318,0.009952,0.003318,0.009952,0.003318,92.029656,8.415524
136,137,12718.2,0.62313,0.44111,0.00685,0.77313,0.68264,0.72843,0.53479,0.96182,...,0.009804,0.003268,0.009804,0.003268,0.009804,0.003268,0.009804,0.003268,91.608435,8.417042
137,138,12810.6,0.61311,0.43786,0.00672,0.78012,0.67502,0.72694,0.53428,0.95916,...,0.009655,0.003219,0.009655,0.003219,0.009655,0.003219,0.009655,0.003219,92.436721,8.414891
138,139,12903.1,0.60941,0.43801,0.00671,0.75794,0.69310,0.72774,0.53530,0.95841,...,0.009507,0.003169,0.009507,0.003169,0.009507,0.003169,0.009507,0.003169,92.472766,8.418847
139,140,12995.8,0.61319,0.43642,0.00668,0.76822,0.68017,0.72628,0.53560,0.96203,...,0.009359,0.003119,0.009359,0.003119,0.009359,0.003119,0.009359,0.003119,92.739680,8.415326

## 5. Common validation and held-out test evaluation

Predict at confidence floor 0.0001 with maximum 100 detections. Select each head's threshold using validation micro F1 at matching IoU 0.50; ties choose the highest threshold. Freeze its checkpoint/hash and threshold before test scoring. Final AP/AR uses the same pycocotools evaluator as RF-DETR, rather than comparing framework-native AP implementations.

Reports include per-class AP/precision/recall/F1, aggregate metrics, PR/confidence curves, raw and normalized confusion matrices including background, and annotated successes/errors. Wrong species contributes one false positive and one false negative. Loss scales are model-specific.

In [5]:
predict_run(RUN)
metrics = evaluate_run(RUN, DATA, heads=CFG["heads"])
for head, splits in metrics.items():
    print(head, {split: result["coco"]["mAP_50_95"] for split, result in splits.items()})
print("Reports:", RUN / "reports")

accuracy/valid: 200/1282 images
accuracy/valid: 400/1282 images
accuracy/valid: 600/1282 images
accuracy/valid: 800/1282 images
accuracy/valid: 1000/1282 images
accuracy/valid: 1200/1282 images
accuracy/test: 200/1284 images
accuracy/test: 400/1284 images
accuracy/test: 600/1284 images
accuracy/test: 800/1284 images
accuracy/test: 1000/1284 images
accuracy/test: 1200/1284 images
end2end/valid: 200/1282 images
end2end/valid: 400/1282 images
end2end/valid: 600/1282 images
end2end/valid: 800/1282 images
end2end/valid: 1000/1282 images
end2end/valid: 1200/1282 images
end2end/test: 200/1284 images
end2end/test: 400/1284 images
end2end/test: 600/1284 images
end2end/test: 800/1284 images
end2end/test: 1000/1284 images
end2end/test: 1200/1284 images
accuracy {'valid': 0.528389424456416, 'test': 0.5312803908581714}
end2end {'valid': 0.5468580509703936, 'test': 0.5483547564197625}
Reports: /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/reports

## 6. Local GPU and CPU latency

Benchmark identical seeded validation images, batch one, FP32, 20 warm-up calls, and one CPU thread. Include preprocessing/inference/postprocessing; exclude decoding. GPU timing synchronizes CUDA. No compilation or TF32. Save every image timing, mean/median/p95, FPS, hardware, checkpoint, threshold, and timing protocol. These measure local PyTorch performance; deployment-device timing requires a separate experiment.

In [6]:
benchmarks = benchmark_run(RUN)
import pandas as pd
display(pd.DataFrame([{k: row[k] for k in ("head", "device", "mean_ms", "median_ms", "p95_ms", "throughput_fps")} for row in benchmarks]))

accuracy/cuda: mean 23.91 ms, p95 24.61 ms
accuracy/cpu: mean 116.48 ms, p95 127.25 ms
end2end/cuda: mean 23.56 ms, p95 24.30 ms
end2end/cpu: mean 127.92 ms, p95 141.53 ms

       head device     mean_ms   median_ms      p95_ms  throughput_fps
0  accuracy   cuda   23.911235   23.974351   24.613658       41.821345
1  accuracy    cpu  116.484016  116.053127  127.245818        8.584869
2   end2end   cuda   23.564081   23.558683   24.295340       42.437470
3   end2end    cpu  127.923669  126.111658  141.533559        7.817162

## 7. Package and optional explicit tracking

Export verified native best weights, class order, frozen thresholds, checkpoint/dataset hashes, model card, and report archive. Automatic framework tracking is disabled. If ClearML credentials exist privately in `.env`, this cell uploads explicit reports and metrics. Failures preserve local reports and a retry queue; no credentials are written into notebook outputs.

In [7]:
best_weights = package_run(RUN)
print("Verified best weights:", best_weights)
print("Recovery checkpoint:", RUN / "native/weights/last_resumable.pt")
print("Report archive:", RUN / "reports.zip")

ClearML Task: created new task id=2a551c380cc54b9888115b0ef64d4dc7
ClearML results page: https://app.clear.ml/projects/11ca3d88c4fe47ff86ffb8ecccdc8142/tasks/2a551c380cc54b9888115b0ef64d4dc7/output/log

███████████████████████████████ 100% | 19.37/19.37 MB [00:00<00:00, 55.24MB/s]:

Verified best weights: /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/weights/best.pt
Recovery checkpoint: /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/native/weights/last_resumable.pt
Report archive: /home/ss3813/github/ML/CSCI-635-ML-Project/output_yolo26/runs/20260928T202126Z-e14d4f/reports.zip

## References

- [YOLO26 models and inference heads](https://docs.ultralytics.com/models/yolo26/)
- [Original YOLOv5 source](https://github.com/ultralytics/yolov5)
- [YOLOv5 versus YOLOv5u compatibility](https://docs.ultralytics.com/models/yolov5/)
- [Ultralytics training settings](https://docs.ultralytics.com/modes/train/)